apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: josephakayesi/web:v0.0.3 # <-- replace/tag accordingly
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
